services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_HOST=0.0.0.0
      - APP_PORT=8080

  test:
    build: .
    command: python -m pytest
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1