name: Release Pipeline

on:
  push:
    branches: [staging]

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Verificar codigo com flake8
        run: |
          flake8 src/ main.py --max-line-length=120 || true

      - name: Rodar testes
        run: |
          python -m pytest src/tests/ -v

      - name: Checar sintaxe
        run: |
          python -m py_compile main.py
          find src/ -name "*.py" -exec python -m py_compile {} \;

      - name: Descobrir proxima tag
        id: tag
        run: |
          # Ver qual a ultima tag rc no formato rc-X.Y (conforme especificação)
          ULTIMA_TAG=$(git tag -l "rc-*.*" | grep -E "^rc-[0-9]+\.[0-9]+$" | sort -V | tail -n 1)
          
          if [ -z "$ULTIMA_TAG" ]; then
            NOVA_TAG="rc-1.0"
          else
            # Extrair X e Y da tag rc-X.Y
            X=$(echo $ULTIMA_TAG | sed 's/rc-\([0-9]*\)\.\([0-9]*\)/\1/')
            Y=$(echo $ULTIMA_TAG | sed 's/rc-\([0-9]*\)\.\([0-9]*\)/\2/')
            
            # Incrementar Y em 1 (ex: rc-2.3 → rc-2.4)
            NOVO_Y=$((Y + 1))
            NOVA_TAG="rc-${X}.${NOVO_Y}"
          fi
          
          echo "tag_anterior=$ULTIMA_TAG" >> $GITHUB_OUTPUT
          echo "nova_tag=$NOVA_TAG" >> $GITHUB_OUTPUT

      - name: Criar zip do sistema
        run: |
          mkdir release
          cp -r src/ release/
          cp main.py requirements.txt README.md release/
          echo "${{ steps.tag.outputs.nova_tag }}" > release/versao.txt
          cd release
          zip -r "../${{ steps.tag.outputs.nova_tag }}.zip" .
          cd ..
          ls *.zip

      - name: Criar tag no git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.tag.outputs.nova_tag }}
          git push origin ${{ steps.tag.outputs.nova_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir arquivo para download
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.tag.outputs.nova_tag }}
          path: ${{ steps.tag.outputs.nova_tag }}.zip
          if-no-files-found: error
